package com.loresuelvo.consumer.domain.diagnosis

/**
 * Single message exchanged with the AI diagnostic assistant.
 *
 *  - [id] is generated by the client (`user-<uuid>`) for the optimistic
 *    append, or by the backend for persisted exchanges; it always
 *    acts as a stable identity for `LazyColumn` keys.
 *  - [sender] discriminates between the consumer's typed prompt
 *    ([Sender.Consumer]) and the AI's reply ([Sender.Assistant]).
 *  - [content] is the message body in plain text — formatting lives
 *    in the UI layer, not in domain.
 *  - [sentAtEpochMillis] is `System.currentTimeMillis()` for client
 *    timestamps or the backend's `created_on` parsed to millis.
 *    Stored as `Long` (not `java.time.Instant`) because `minSdk = 24`
 *    predates `java.time`; the UI converts to a localized timestamp
 *    for display.
 *  - [images] are server-issued references to photos attached to
 *    this message. They are empty for text-only messages.
 *
 * No `status`, `recommendations`, or `assessment` are attached to a
 * single message: those concerns belong to the enclosing [Diagnosis]
 * aggregate.
 */
data class ChatMessage(
    val id: String,
    val sender: Sender,
    val content: String,
    val sentAtEpochMillis: Long,
    val images: List<ChatImage> = emptyList(),
)
